name: Cypress Tests and TestRail Integration

on:
  push:
    branches:
      - main

env:
  TESTRAIL_USER: gr.eg.or.ymj.en.son6@gmail.com
  TESTRAIL_USER_PW: TestRail*1
  TESTRAIL_URL: https://swe401pro.testrail.io/
  PROJECT_NAME: SWE 401

jobs:
  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --reporter junit --reporter-options mochaFile=reports/TEST-[hash].xml

      - name: Upload results to TestRail
        run: |
          pip install trcli
          junitparser merge --glob "reports/TEST-*" "reports/junit-report.xml"
          trcli -y \
            -h ${{ env.TESTRAIL_URL }} \
            --project "${{ env.PROJECT_NAME }}" \
            -u ${{ env.TESTRAIL_USER }} \
            -p "${{ env.TESTRAIL_USER_PW }}" \
            parse_junit \
            -f "reports/junit-report.xml" \
            --section-id "2407" \
            --title "Cypress automated tests" \
            --run-description "GitHub workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"