on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  
name: Test

env:
  TESTRAIL_USER: gr.eg.or.ymj.en.son6@gmail.com
  TESTRAIL_USER_PW: TestRail*1
  TESTRAIL_URL: https://swe401pro.testrail.io/
  PROJECT_NAME: SWE 401

jobs: 
 
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: samples/javascript/cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute Cypress tests
        continue-on-error: true
        uses: cypress-io/github-action@v5.3.0
        with:
          command: npx cypress run --reporter junit --reporter-options mochaFile=reports/TEST-[hash].xml
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with: 
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and save results
        id: test
        run: |
          pytest --junitxml=results.xml --result-log=result.log
          echo "::set-output name=test-results::result.log"
      - name: Execute TestRail CLI to upload results
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          pip install requests
          python send_results.py ${{ env.TESTRAIL_URL }} ${{ env.TESTRAIL_USER }} ${{ env.TESTRAIL_USER_PW }} ${{ steps.test.outputs.test-results }}