on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  
name: Test

env:
  TESTRAIL_USER: gr.eg.or.ymj.en.son6@gmail.com
  TESTRAIL_USER_PW: TestRail*1
  TESTRAIL_URL: https://swe401pro.testrail.io/
  PROJECT_NAME: SWE 401

jobs: 
 
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: samples/javascript/cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute Cypress tests
        continue-on-error: true
        uses: cypress-io/github-action@v5.3.0
        with:
          command: npx cypress run --reporter junit --reporter-options mochaFile=reports/TEST-[hash].xml
      - name: Todo smokey
        with: 
          command: npx cypress run --spec path/todo_app/todo_smoke.cy.js
      - name: Todo interactions
        with:
          command: npx cypress run --spec e2e/todo_app/todo_interactions.cy.js
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with: 
          python-version: '3.x'
      - name: Execute TestRail CLI to upload results
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          pip install trcli
          junitparser merge --glob "sample_reports/TEST-*" "sample_reports/junit-report.xml"
          trcli -y \
            -h ${{ env.TESTRAIL_URL }} \
            --project "${{ env.PROJECT_NAME }}" \
            -u ${{ env.TESTRAIL_USER }} \
            -p "${{ env.TESTRAIL_USER_PW }}" \
            parse_junit \
            -f "sample_reports/junit-report.xml" \
            --title "Cypress automated tests" \
            --run-description "GitHub workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
